spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    property-naming-strategy: SNAKE_CASE

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_POST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jwt:
    key: ${JWT_KEY}
    live:
      atk: ${ACCESSTOKEN_LIVE}
      rtk: ${REFRESHTOKEN_LIVE}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    stack:
      auto: false