spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  jwt:
    key: ${JWT_KEY}
    live:
      atk: ${ACCESSTOKEN_LIVE}
      rtk: ${REFRESHTOKEN_LIVE}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true