spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  jwt:
    key: ${JWT_KEY}
    atk: ${JWT_ATK}
    rtk: ${JWT_RTK}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
